### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "John Ko kafka testing",
  "email": "john_testing277@gmail.com",
  "address": "123 street",
  "dateOfBirth": "1999-05-03",
  "registeredDate": "2025-12-25"
}

###